name: Run Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
    branches:
      - main
      - '*.x'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1, 8.0]
        laravel: [10.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 9.*
            testbench: ^7.0
        exclude:
          - laravel: 10.*
            php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, exif, iconv, tokenizer
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
