name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
    branches:
      - main
      - '*.x'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2.5, 7.3, 7.4, 8.0, 8.1, 8.2 ]
        laravel: [ 7.*, 8.*, 9.*, 10.x ]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
        exclude:
          - laravel: 7.*
            php: 7.4
          - laravel: 7.*
            php: 8.0

          - laravel: 8.*
            php: 7.2.5
          - laravel: 8.*
            php: 8.2

          - laravel: 9.*
            php: 7.2.5
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4

          - laravel: 10.*
            php: 7.2.5
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0

    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Update apt
        run: sudo apt-get update --fix-missing

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/console:${{ matrix.laravel }}" "illuminate/database:${{ matrix.laravel }}" "illuminate/filesystem:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest
      - name: Execute tests
        run: vendor/bin/phpunit
